import vapoursynth as vs
from typing import Any, Tuple, Union

core: Any

def fade_filter(clip: vs.VideoNode, clip_a: vs.VideoNode, clip_b: vs.VideoNode, start_f: int, end_f: int) -> vs.VideoNode: ...
def merge_chroma(luma: vs.VideoNode, ref: vs.VideoNode) -> vs.VideoNode: ...
def get_chroma_shift(src_h: int, dst_h: int, aspect_ratio: float=...) -> float: ...
def get_bicubic_params(cubic_filter: str) -> Tuple[float, float]: ...
def generate_keyframes(clip: vs.VideoNode, out_path: str) -> None: ...
def set_ffms2_log_level(level: Union[str, int]=...) -> None: ...
